---
pipeline:
  thing1:
    image: debian:jessie
    commands:
      - echo hi
  thing2:
    image: debian:jessie
    commands:
      - echo hi
  thing3:
    image: debian:jessie
    commands:
      - echo hi


notify:
  slack:
    webhook_url: "https://hooks.slack.com/services/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"
    channel: "#st-johns"
    username: drone
    when:
      branch: master
